import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";
import { createPage } from "./common.js";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

async function main() {
  console.log("=== PHASE 3: Authoritative Seed Data Ingestion ===\n");

  const ids = JSON.parse(fs.readFileSync(path.resolve(__dirname, "ids.json"), "utf8"));

  // 1. Seed Courses (5 rows)
  console.log("1. Seeding 5 Courses...");
  const coursesData = [
    {
      code: "CS2005",
      name: "Programming Concepts using Java",
      credits: 4,
      type: "Theory",
      sctRequired: true,
      sctStatus: "Pending",
      submissionTrack: null,
      etElig: "In Progress",
      oppe1Elig: "In Progress",
      oppe2Elig: "In Progress",
      courseGradeGate: "In Progress",
      gaaSummary: "Not Evaluated (0 / 6 assessed)",
      nextAction: "Complete Week 1 Content & Prepare for A2",
    },
    {
      code: "SE2001",
      name: "System Commands",
      credits: 3,
      type: "Theory",
      sctRequired: true,
      sctStatus: "Pending",
      submissionTrack: null,
      etElig: "In Progress",
      oppe1Elig: "In Progress",
      oppe2Elig: "In Progress",
      courseGradeGate: "In Progress",
      gaaSummary: "Not Evaluated (0 / 9 assessed)",
      nextAction: "Complete Week 1 GA1 & System Commands Practice",
    },
    {
      code: "CS2006",
      name: "Application Development II",
      credits: 4,
      type: "Theory",
      sctRequired: false,
      sctStatus: "N/A",
      submissionTrack: null,
      etElig: "In Progress",
      oppe1Elig: "N/A",
      oppe2Elig: "N/A",
      courseGradeGate: "In Progress",
      gaaSummary: "Not Evaluated (0 / 2 assessed)",
      nextAction: "Complete Week 1 GA1 & PA1",
    },
    {
      code: "CS2006P",
      name: "Application Development II - Project",
      credits: 2,
      type: "Project",
      sctRequired: false,
      sctStatus: "N/A",
      submissionTrack: "Unset",
      etElig: "Eligible (Project Course)",
      oppe1Elig: "N/A",
      oppe2Elig: "N/A",
      courseGradeGate: "In Progress",
      gaaSummary: "N/A (Project Course)",
      nextAction: "Stage 0: Git Tracker Registration (Due Oct 25)",
    },
    {
      code: "MS2001",
      name: "Business Data Management",
      credits: 4,
      type: "Theory",
      sctRequired: false,
      sctStatus: "N/A",
      submissionTrack: null,
      etElig: "In Progress",
      oppe1Elig: "N/A",
      oppe2Elig: "N/A",
      courseGradeGate: "In Progress",
      gaaSummary: "Not Evaluated (0 / 9 assessed)",
      nextAction: "Complete Week 1 GA1 Business Case Analysis",
    },
  ];

  const coursePageMap = {};
  for (const c of coursesData) {
    const props = {
      "Course Code": { title: [{ type: "text", text: { content: c.code } }] },
      "Course Name": { rich_text: [{ type: "text", text: { content: c.name } }] },
      Credits: { number: c.credits },
      Type: { select: { name: c.type } },
      "SCT Required": { checkbox: c.sctRequired },
      "SCT Status": { select: { name: c.sctStatus } },
      "ET Eligibility": { select: { name: c.etElig } },
      "OPPE1 Eligibility": { select: { name: c.oppe1Elig } },
      "OPPE2 Eligibility": { select: { name: c.oppe2Elig } },
      "Course Grade Gate": { select: { name: c.courseGradeGate } },
      "GAA Summary": { rich_text: [{ type: "text", text: { content: c.gaaSummary } }] },
      "Next Action": { rich_text: [{ type: "text", text: { content: c.nextAction } }] },
    };
    if (c.submissionTrack) {
      props["Submission Track"] = { select: { name: c.submissionTrack } };
    }

    const page = await createPage({ database_id: ids.databases.courses }, props);
    coursePageMap[c.code] = page.id;
    console.log(`   Created Course [${c.code}]: ${page.id}`);
  }

  const allCourseIds = Object.values(coursePageMap);
  const sctCourseIds = [coursePageMap["CS2005"], coursePageMap["SE2001"]];

  // 2. Seed Academic Items (Exactly 77 rows)
  console.log("\n2. Seeding exactly 77 Academic Items...");

  const academicItemsData = [
    // --- CS2005: 19 rows ---
    {
      name: "CS2005 · A2",
      code: "A2",
      type: "Programming Assignment",
      week: 2,
      date: "2026-10-18T23:59:00+05:30",
      gaa: true,
      et: false,
      oppe1: true,
      oppe2: false,
      courses: ["CS2005"],
    },
    {
      name: "CS2005 · A3",
      code: "A3",
      type: "Programming Assignment",
      week: 3,
      date: "2026-10-25T23:59:00+05:30",
      gaa: true,
      et: false,
      oppe1: true,
      oppe2: false,
      courses: ["CS2005"],
    },
    {
      name: "CS2005 · A4",
      code: "A4",
      type: "Programming Assignment",
      week: 4,
      date: "2026-11-01T23:59:00+05:30",
      gaa: true,
      et: false,
      oppe1: true,
      oppe2: false,
      courses: ["CS2005"],
    },
    {
      name: "CS2005 · A5",
      code: "A5",
      type: "Programming Assignment",
      week: 5,
      date: "2026-11-11T23:59:00+05:30",
      gaa: true,
      et: false,
      oppe1: false,
      oppe2: true,
      courses: ["CS2005"],
    },
    {
      name: "CS2005 · A6",
      code: "A6",
      type: "Programming Assignment",
      week: 6,
      date: "2026-11-18T23:59:00+05:30",
      gaa: true,
      et: false,
      oppe1: false,
      oppe2: true,
      courses: ["CS2005"],
    },
    {
      name: "CS2005 · A7",
      code: "A7",
      type: "Programming Assignment",
      week: 7,
      date: "2026-11-25T23:59:00+05:30",
      gaa: true,
      et: false,
      oppe1: false,
      oppe2: true,
      courses: ["CS2005"],
    },
    {
      name: "CS2005 · A8",
      code: "A8",
      type: "Programming Assignment",
      week: 8,
      date: "2026-11-29T23:59:00+05:30",
      gaa: true,
      et: false,
      oppe1: false,
      oppe2: true,
      courses: ["CS2005"],
    },
    {
      name: "CS2005 · GA1",
      code: "GA1",
      type: "Weekly Assessment",
      week: 1,
      date: "2026-10-11T23:59:00+05:30",
      gaa: false,
      et: true,
      oppe1: false,
      oppe2: false,
      courses: ["CS2005"],
    },
    {
      name: "CS2005 · GA2",
      code: "GA2",
      type: "Weekly Assessment",
      week: 2,
      date: "2026-10-18T23:59:00+05:30",
      gaa: false,
      et: true,
      oppe1: false,
      oppe2: false,
      courses: ["CS2005"],
    },
    {
      name: "CS2005 · GA3",
      code: "GA3",
      type: "Weekly Assessment",
      week: 3,
      date: "2026-10-25T23:59:00+05:30",
      gaa: false,
      et: true,
      oppe1: false,
      oppe2: false,
      courses: ["CS2005"],
    },
    {
      name: "CS2005 · GA4",
      code: "GA4",
      type: "Weekly Assessment",
      week: 4,
      date: "2026-11-01T23:59:00+05:30",
      gaa: false,
      et: true,
      oppe1: false,
      oppe2: false,
      courses: ["CS2005"],
    },
    {
      name: "CS2005 · GA5",
      code: "GA5",
      type: "Weekly Assessment",
      week: 5,
      date: "2026-11-11T23:59:00+05:30",
      gaa: false,
      et: true,
      oppe1: false,
      oppe2: false,
      courses: ["CS2005"],
    },
    {
      name: "CS2005 · GA6",
      code: "GA6",
      type: "Weekly Assessment",
      week: 6,
      date: "2026-11-18T23:59:00+05:30",
      gaa: false,
      et: true,
      oppe1: false,
      oppe2: false,
      courses: ["CS2005"],
    },
    {
      name: "CS2005 · GA7",
      code: "GA7",
      type: "Weekly Assessment",
      week: 7,
      date: "2026-11-25T23:59:00+05:30",
      gaa: false,
      et: true,
      oppe1: false,
      oppe2: false,
      courses: ["CS2005"],
    },
    {
      name: "CS2005 · Quiz 1",
      code: "QZ1",
      type: "Quiz",
      week: null,
      date: "2026-11-15T14:00:00+05:30",
      gaa: false,
      et: true,
      oppe1: false,
      oppe2: false,
      hardCutoff: true,
      courses: ["CS2005"],
    },
    {
      name: "CS2005 · Quiz 2",
      code: "QZ2",
      type: "Quiz",
      week: null,
      date: "2026-12-05T14:00:00+05:30",
      gaa: false,
      et: true,
      oppe1: false,
      oppe2: false,
      hardCutoff: true,
      courses: ["CS2005"],
    },
    {
      name: "CS2005 · OPPE 1",
      code: "PE1",
      type: "OPPE",
      week: null,
      date: "2026-11-22T09:00:00+05:30",
      gaa: false,
      et: false,
      oppe1: false,
      oppe2: false,
      hardCutoff: true,
      courses: ["CS2005"],
    },
    {
      name: "CS2005 · OPPE 2",
      code: "PE2",
      type: "OPPE",
      week: null,
      date: "2026-12-20T09:00:00+05:30",
      gaa: false,
      et: false,
      oppe1: false,
      oppe2: false,
      hardCutoff: true,
      courses: ["CS2005"],
    },
    {
      name: "CS2005 · End Term Exam",
      code: "ET",
      type: "End Term",
      week: null,
      date: "2027-01-10T09:00:00+05:30",
      gaa: false,
      et: false,
      oppe1: false,
      oppe2: false,
      hardCutoff: true,
      courses: ["CS2005"],
    },

    // --- SE2001: 18 rows ---
    {
      name: "SE2001 · GA1",
      code: "GA1",
      type: "Weekly Assessment",
      week: 1,
      date: "2026-10-11T23:59:00+05:30",
      gaa: true,
      et: true,
      oppe1: false,
      oppe2: false,
      courses: ["SE2001"],
    },
    {
      name: "SE2001 · GA2",
      code: "GA2",
      type: "Weekly Assessment",
      week: 2,
      date: "2026-10-18T23:59:00+05:30",
      gaa: true,
      et: true,
      oppe1: false,
      oppe2: false,
      courses: ["SE2001"],
    },
    {
      name: "SE2001 · GA3",
      code: "GA3",
      type: "Weekly Assessment",
      week: 3,
      date: "2026-10-25T23:59:00+05:30",
      gaa: true,
      et: true,
      oppe1: false,
      oppe2: false,
      courses: ["SE2001"],
    },
    {
      name: "SE2001 · GA4",
      code: "GA4",
      type: "Weekly Assessment",
      week: 4,
      date: "2026-11-01T23:59:00+05:30",
      gaa: true,
      et: true,
      oppe1: false,
      oppe2: false,
      courses: ["SE2001"],
    },
    {
      name: "SE2001 · GA5",
      code: "GA5",
      type: "Weekly Assessment",
      week: 5,
      date: "2026-11-11T23:59:00+05:30",
      gaa: true,
      et: true,
      oppe1: false,
      oppe2: false,
      courses: ["SE2001"],
    },
    {
      name: "SE2001 · GA6",
      code: "GA6",
      type: "Weekly Assessment",
      week: 6,
      date: "2026-11-18T23:59:00+05:30",
      gaa: true,
      et: true,
      oppe1: false,
      oppe2: false,
      courses: ["SE2001"],
    },
    {
      name: "SE2001 · GA7",
      code: "GA7",
      type: "Weekly Assessment",
      week: 7,
      date: "2026-11-25T23:59:00+05:30",
      gaa: true,
      et: true,
      oppe1: false,
      oppe2: false,
      courses: ["SE2001"],
    },
    {
      name: "SE2001 · GA8",
      code: "GA8",
      type: "Weekly Assessment",
      week: 8,
      date: "2026-12-02T23:59:00+05:30",
      gaa: true,
      et: false,
      oppe1: false,
      oppe2: false,
      courses: ["SE2001"],
    },
    {
      name: "SE2001 · GA9",
      code: "GA9",
      type: "Weekly Assessment",
      week: 9,
      date: "2026-12-09T23:59:00+05:30",
      gaa: true,
      et: false,
      oppe1: false,
      oppe2: false,
      courses: ["SE2001"],
    },
    {
      name: "SE2001 · GA10",
      code: "GA10",
      type: "Weekly Assessment",
      week: 10,
      date: "2026-12-16T23:59:00+05:30",
      gaa: true,
      et: false,
      oppe1: false,
      oppe2: false,
      courses: ["SE2001"],
    },
    {
      name: "SE2001 · BPT 1",
      code: "BPT1",
      type: "BPT",
      week: 3,
      date: "2026-10-23T23:59:00+05:30",
      gaa: false,
      et: false,
      oppe1: true,
      oppe2: false,
      courses: ["SE2001"],
    },
    {
      name: "SE2001 · BPT 2",
      code: "BPT2",
      type: "BPT",
      week: 5,
      date: "2026-11-06T23:59:00+05:30",
      gaa: false,
      et: false,
      oppe1: true,
      oppe2: false,
      courses: ["SE2001"],
    },
    {
      name: "SE2001 · BPT 3",
      code: "BPT3",
      type: "BPT",
      week: 7,
      date: "2026-11-20T23:59:00+05:30",
      gaa: false,
      et: false,
      oppe1: true,
      oppe2: false,
      hardCutoff: true,
      courses: ["SE2001"],
    },
    {
      name: "SE2001 · BPT 4",
      code: "BPT4",
      type: "BPT",
      week: 10,
      date: "2026-12-11T23:59:00+05:30",
      gaa: false,
      et: false,
      oppe1: false,
      oppe2: false,
      courses: ["SE2001"],
    },
    {
      name: "SE2001 · Quiz 1",
      code: "QZ1",
      type: "Quiz",
      week: null,
      date: "2026-11-15T10:00:00+05:30",
      gaa: false,
      et: true,
      oppe1: false,
      oppe2: false,
      hardCutoff: true,
      courses: ["SE2001"],
    },
    {
      name: "SE2001 · OPPE",
      code: "OPPE",
      type: "OPPE",
      week: null,
      date: "2026-12-20T14:00:00+05:30",
      gaa: false,
      et: false,
      oppe1: false,
      oppe2: false,
      hardCutoff: true,
      courses: ["SE2001"],
    },
    {
      name: "SE2001 · ReOPPE",
      code: "REOPPE",
      type: "ReOPPE",
      week: null,
      date: "2027-01-03T14:00:00+05:30",
      gaa: false,
      et: false,
      oppe1: false,
      oppe2: false,
      hardCutoff: true,
      courses: ["SE2001"],
    },
    {
      name: "SE2001 · End Term Exam",
      code: "ET",
      type: "End Term",
      week: null,
      date: "2027-01-10T14:00:00+05:30",
      gaa: false,
      et: false,
      oppe1: false,
      oppe2: false,
      hardCutoff: true,
      courses: ["SE2001"],
    },

    // --- CS2006: 12 rows ---
    {
      name: "CS2006 · PA1",
      code: "PA1",
      type: "Programming Assignment",
      week: 1,
      date: "2026-10-11T23:59:00+05:30",
      gaa: true,
      et: false,
      oppe1: false,
      oppe2: false,
      courses: ["CS2006"],
    },
    {
      name: "CS2006 · PA2",
      code: "PA2",
      type: "Programming Assignment",
      week: 2,
      date: "2026-10-18T23:59:00+05:30",
      gaa: true,
      et: false,
      oppe1: false,
      oppe2: false,
      courses: ["CS2006"],
    },
    {
      name: "CS2006 · GA1",
      code: "GA1",
      type: "Weekly Assessment",
      week: 1,
      date: "2026-10-11T23:59:00+05:30",
      gaa: false,
      et: true,
      oppe1: false,
      oppe2: false,
      courses: ["CS2006"],
    },
    {
      name: "CS2006 · GA2",
      code: "GA2",
      type: "Weekly Assessment",
      week: 2,
      date: "2026-10-18T23:59:00+05:30",
      gaa: false,
      et: true,
      oppe1: false,
      oppe2: false,
      courses: ["CS2006"],
    },
    {
      name: "CS2006 · GA3",
      code: "GA3",
      type: "Weekly Assessment",
      week: 3,
      date: "2026-10-25T23:59:00+05:30",
      gaa: false,
      et: true,
      oppe1: false,
      oppe2: false,
      courses: ["CS2006"],
    },
    {
      name: "CS2006 · GA4",
      code: "GA4",
      type: "Weekly Assessment",
      week: 4,
      date: "2026-11-01T23:59:00+05:30",
      gaa: false,
      et: true,
      oppe1: false,
      oppe2: false,
      courses: ["CS2006"],
    },
    {
      name: "CS2006 · GA5",
      code: "GA5",
      type: "Weekly Assessment",
      week: 5,
      date: "2026-11-11T23:59:00+05:30",
      gaa: false,
      et: true,
      oppe1: false,
      oppe2: false,
      courses: ["CS2006"],
    },
    {
      name: "CS2006 · GA6",
      code: "GA6",
      type: "Weekly Assessment",
      week: 6,
      date: "2026-11-18T23:59:00+05:30",
      gaa: false,
      et: true,
      oppe1: false,
      oppe2: false,
      courses: ["CS2006"],
    },
    {
      name: "CS2006 · GA7",
      code: "GA7",
      type: "Weekly Assessment",
      week: 7,
      date: "2026-11-25T23:59:00+05:30",
      gaa: false,
      et: true,
      oppe1: false,
      oppe2: false,
      courses: ["CS2006"],
    },
    {
      name: "CS2006 · Quiz 1",
      code: "QZ1",
      type: "Quiz",
      week: null,
      date: "2026-11-15T10:00:00+05:30",
      gaa: false,
      et: true,
      oppe1: false,
      oppe2: false,
      hardCutoff: true,
      courses: ["CS2006"],
    },
    {
      name: "CS2006 · Quiz 2",
      code: "QZ2",
      type: "Quiz",
      week: null,
      date: "2026-12-05T10:00:00+05:30",
      gaa: false,
      et: true,
      oppe1: false,
      oppe2: false,
      hardCutoff: true,
      courses: ["CS2006"],
    },
    {
      name: "CS2006 · End Term Exam",
      code: "ET",
      type: "End Term",
      week: null,
      date: "2027-01-10T14:00:00+05:30",
      gaa: false,
      et: false,
      oppe1: false,
      oppe2: false,
      hardCutoff: true,
      courses: ["CS2006"],
    },

    // --- MS2001: 12 rows ---
    {
      name: "MS2001 · GA1",
      code: "GA1",
      type: "Weekly Assessment",
      week: 1,
      date: "2026-10-11T23:59:00+05:30",
      gaa: true,
      et: true,
      oppe1: false,
      oppe2: false,
      courses: ["MS2001"],
    },
    {
      name: "MS2001 · GA2",
      code: "GA2",
      type: "Weekly Assessment",
      week: 2,
      date: "2026-10-18T23:59:00+05:30",
      gaa: true,
      et: true,
      oppe1: false,
      oppe2: false,
      courses: ["MS2001"],
    },
    {
      name: "MS2001 · GA3",
      code: "GA3",
      type: "Weekly Assessment",
      week: 3,
      date: "2026-10-25T23:59:00+05:30",
      gaa: true,
      et: true,
      oppe1: false,
      oppe2: false,
      courses: ["MS2001"],
    },
    {
      name: "MS2001 · GA4",
      code: "GA4",
      type: "Weekly Assessment",
      week: 4,
      date: "2026-11-01T23:59:00+05:30",
      gaa: true,
      et: true,
      oppe1: false,
      oppe2: false,
      courses: ["MS2001"],
    },
    {
      name: "MS2001 · GA5",
      code: "GA5",
      type: "Weekly Assessment",
      week: 5,
      date: "2026-11-11T23:59:00+05:30",
      gaa: true,
      et: true,
      oppe1: false,
      oppe2: false,
      courses: ["MS2001"],
    },
    {
      name: "MS2001 · GA6",
      code: "GA6",
      type: "Weekly Assessment",
      week: 6,
      date: "2026-11-18T23:59:00+05:30",
      gaa: true,
      et: true,
      oppe1: false,
      oppe2: false,
      courses: ["MS2001"],
    },
    {
      name: "MS2001 · GA7",
      code: "GA7",
      type: "Weekly Assessment",
      week: 7,
      date: "2026-11-25T23:59:00+05:30",
      gaa: true,
      et: true,
      oppe1: false,
      oppe2: false,
      courses: ["MS2001"],
    },
    {
      name: "MS2001 · GA8",
      code: "GA8",
      type: "Weekly Assessment",
      week: 8,
      date: "2026-12-02T23:59:00+05:30",
      gaa: true,
      et: false,
      oppe1: false,
      oppe2: false,
      courses: ["MS2001"],
    },
    {
      name: "MS2001 · GA9",
      code: "GA9",
      type: "Weekly Assessment",
      week: 9,
      date: "2026-12-09T23:59:00+05:30",
      gaa: true,
      et: false,
      oppe1: false,
      oppe2: false,
      courses: ["MS2001"],
    },
    {
      name: "MS2001 · Quiz 1",
      code: "QZ1",
      type: "Quiz",
      week: null,
      date: "2026-11-15T14:00:00+05:30",
      gaa: false,
      et: true,
      oppe1: false,
      oppe2: false,
      hardCutoff: true,
      courses: ["MS2001"],
    },
    {
      name: "MS2001 · Quiz 2",
      code: "QZ2",
      type: "Quiz",
      week: null,
      date: "2026-12-05T14:00:00+05:30",
      gaa: false,
      et: true,
      oppe1: false,
      oppe2: false,
      hardCutoff: true,
      courses: ["MS2001"],
    },
    {
      name: "MS2001 · End Term Exam",
      code: "ET",
      type: "End Term",
      week: null,
      date: "2027-01-10T09:00:00+05:30",
      gaa: false,
      et: false,
      oppe1: false,
      oppe2: false,
      hardCutoff: true,
      courses: ["MS2001"],
    },

    // --- CS2006P Official Milestones & Deadlines: 5 rows ---
    {
      name: "CS2006P · Git Tracker Registration",
      code: "M0_GIT",
      type: "Project Deadline",
      week: null,
      date: "2026-10-25T23:59:00+05:30",
      gaa: false,
      et: false,
      oppe1: false,
      oppe2: false,
      courses: ["CS2006P"],
      ref: "MAD-2 §1.1",
    },
    {
      name: "CS2006P · Track A Submission Deadline",
      code: "SUB_TRACK_A",
      type: "Project Deadline",
      week: null,
      date: "2026-11-17T23:59:00+05:30",
      gaa: false,
      et: false,
      oppe1: false,
      oppe2: false,
      hardCutoff: true,
      courses: ["CS2006P"],
      ref: "MAD-2 §4.0 (Track A)",
    },
    {
      name: "CS2006P · Track B Submission Deadline",
      code: "SUB_TRACK_B",
      type: "Project Deadline",
      week: null,
      date: "2026-12-10T23:59:00+05:30",
      gaa: false,
      et: false,
      oppe1: false,
      oppe2: false,
      hardCutoff: true,
      courses: ["CS2006P"],
      ref: "MAD-2 §4.0 (Track B)",
    },
    {
      name: "CS2006P · Level 1 Viva Window",
      code: "VIVA_L1",
      type: "Project Deadline",
      week: null,
      date: "2026-12-22T23:59:00+05:30",
      gaa: false,
      et: false,
      oppe1: false,
      oppe2: false,
      hardCutoff: true,
      courses: ["CS2006P"],
      ref: "MAD-2 §5.1",
    },
    {
      name: "CS2006P · Level 2 Viva Window",
      code: "VIVA_L2",
      type: "Project Deadline",
      week: null,
      date: "2027-01-07T23:59:00+05:30",
      gaa: false,
      et: false,
      oppe1: false,
      oppe2: false,
      hardCutoff: true,
      courses: ["CS2006P"],
      ref: "MAD-2 §5.2",
    },

    // --- Global Academic Cutoffs & Milestones: 11 rows ---
    {
      name: "Term Course Registration Closes",
      code: "CUTOFF_REG",
      type: "Academic Milestone",
      week: null,
      date: "2026-09-23T23:59:00+05:30",
      gaa: false,
      et: false,
      oppe1: false,
      oppe2: false,
      hardCutoff: true,
      courses: "ALL",
      ref: "Academic Calendar",
    },
    {
      name: "Academic Term Content Release",
      code: "TERM_START",
      type: "Academic Milestone",
      week: null,
      date: "2026-10-02T00:00:00+05:30",
      gaa: false,
      et: false,
      oppe1: false,
      oppe2: false,
      courses: "ALL",
      ref: "Academic Calendar",
    },
    {
      name: "Course Drop Window Closes",
      code: "DROP_DEADLINE",
      type: "Academic Milestone",
      week: null,
      date: "2026-10-18T23:59:00+05:30",
      gaa: false,
      et: false,
      oppe1: false,
      oppe2: false,
      hardCutoff: true,
      courses: "ALL",
      ref: "Academic Calendar",
    },
    {
      name: "OPPE SCT Window 1 Closes",
      code: "SCT_W1",
      type: "Eligibility Cutoff",
      week: null,
      date: "2026-10-30T23:59:00+05:30",
      gaa: false,
      et: false,
      oppe1: false,
      oppe2: false,
      hardCutoff: true,
      courses: "SCT",
      ref: "SCT Guidelines",
    },
    {
      name: "Week 4 OPPE 1 Eligibility Closes",
      code: "CUTOFF_W4",
      type: "Eligibility Cutoff",
      week: 4,
      date: "2026-11-01T23:59:00+05:30",
      gaa: false,
      et: false,
      oppe1: false,
      oppe2: false,
      hardCutoff: true,
      courses: "SCT",
      ref: "Grading Policy §4",
    },
    {
      name: "OPPE SCT Window 2 Closes",
      code: "SCT_W2",
      type: "Eligibility Cutoff",
      week: null,
      date: "2026-11-16T23:59:00+05:30",
      gaa: false,
      et: false,
      oppe1: false,
      oppe2: false,
      hardCutoff: true,
      courses: "SCT",
      ref: "SCT Guidelines",
    },
    {
      name: "Week 7 End Term Eligibility Closes",
      code: "CUTOFF_W7",
      type: "Eligibility Cutoff",
      week: 7,
      date: "2026-11-25T23:59:00+05:30",
      gaa: false,
      et: false,
      oppe1: false,
      oppe2: false,
      hardCutoff: true,
      courses: "ALL",
      ref: "Grading Policy §2",
    },
    {
      name: "Week 8 OPPE 2 Eligibility Closes",
      code: "CUTOFF_W8",
      type: "Eligibility Cutoff",
      week: 8,
      date: "2026-11-29T23:59:00+05:30",
      gaa: false,
      et: false,
      oppe1: false,
      oppe2: false,
      hardCutoff: true,
      courses: ["CS2005"],
      ref: "CS2005 Grading Policy",
    },
    {
      name: "OPPE SCT Window 3 Closes",
      code: "SCT_W3",
      type: "Eligibility Cutoff",
      week: null,
      date: "2026-12-11T23:59:00+05:30",
      gaa: false,
      et: false,
      oppe1: false,
      oppe2: false,
      hardCutoff: true,
      courses: "SCT",
      ref: "SCT Guidelines",
    },
    {
      name: "Week 10 GAA Calculation Closes",
      code: "CUTOFF_W10",
      type: "Eligibility Cutoff",
      week: 10,
      date: "2026-12-13T23:59:00+05:30",
      gaa: false,
      et: false,
      oppe1: false,
      oppe2: false,
      hardCutoff: true,
      courses: "ALL",
      ref: "Grading Policy §3",
    },
    {
      name: "OPPE SCT Window 4 Closes",
      code: "SCT_W4",
      type: "Eligibility Cutoff",
      week: null,
      date: "2026-12-28T23:59:00+05:30",
      gaa: false,
      et: false,
      oppe1: false,
      oppe2: false,
      hardCutoff: true,
      courses: "SCT",
      ref: "SCT Guidelines",
    },
  ];

  console.log(`   Total items in manifest: ${academicItemsData.length}`);
  if (academicItemsData.length !== 77) {
    throw new Error(`Manifest must have exactly 77 rows, found ${academicItemsData.length}`);
  }

  const academicItemMap = {};
  for (let i = 0; i < academicItemsData.length; i++) {
    const item = academicItemsData[i];
    let linkedCourses = [];
    if (item.courses === "ALL") {
      linkedCourses = allCourseIds.map((id) => ({ id }));
    } else if (item.courses === "SCT") {
      linkedCourses = sctCourseIds.map((id) => ({ id }));
    } else if (Array.isArray(item.courses)) {
      linkedCourses = item.courses.map((code) => ({ id: coursePageMap[code] }));
    }

    const props = {
      "Item Name": { title: [{ type: "text", text: { content: item.name } }] },
      "Assessment Code": { select: { name: item.code } },
      "Item Type": { select: { name: item.type } },
      Date: { date: { start: item.date } },
      Status: { select: { name: "Pending" } },
      "Max Score": { number: 100 },
      "Hard Cutoff": { checkbox: !!item.hardCutoff },
      "Counts Toward GAA": { checkbox: !!item.gaa },
      "Counts Toward ET Eligibility": { checkbox: !!item.et },
      "Counts Toward OPPE1": { checkbox: !!item.oppe1 },
      "Counts Toward OPPE2": { checkbox: !!item.oppe2 },
      Course: { relation: linkedCourses },
    };
    if (item.week !== null && item.week !== undefined) {
      props["Week"] = { number: item.week };
    }
    if (item.ref) {
      props["Reference"] = { rich_text: [{ type: "text", text: { content: item.ref } }] };
    }

    const page = await createPage({ database_id: ids.databases.academicItems }, props);
    academicItemMap[item.code] = page.id;
    if (item.courses.includes && item.courses.includes("CS2006P")) {
      academicItemMap[`${item.code}_CS2006P`] = page.id;
    }
    if (i % 10 === 0 || i === academicItemsData.length - 1) {
      console.log(`   Seeded ${i + 1}/${academicItemsData.length} items...`);
    }
  }

  // 3. Seed Project Tracker (Exactly 37 rows)
  console.log("\n3. Seeding exactly 37 Project Tracker rows...");

  const cs2006pCourseRelation = [{ id: coursePageMap["CS2006P"] }];

  // 3.1: 9 Sequential Stages
  const stages = [
    {
      title: "Stage 0: Git Tracker Registration",
      order: 0,
      academicCode: "M0_GIT",
      src: "MAD-2 §1.1",
    },
    { title: "Stage 1: Application Development", order: 1, academicCode: null, src: "TMA V2 §2.0" },
    {
      title: "Stage 2: Pre-Submission Validation Form",
      order: 2,
      academicCode: null,
      src: "MAD-2 §3.1",
    },
    {
      title: "Stage 3: Final Portal Submission",
      order: 3,
      academicCode: "SUB_TRACK_A",
      src: "MAD-2 §4.0",
    },
    {
      title: "Stage 4: Automated Portal Validation",
      order: 4,
      academicCode: null,
      src: "MAD-2 §4.2",
    },
    {
      title: "Stage 5: Plagiarism & Originality Screening",
      order: 5,
      academicCode: null,
      src: "MAD-2 §4.4",
    },
    {
      title: "Stage 6: Level 1 Viva (Max 40)",
      order: 6,
      maxScore: 40,
      academicCode: "VIVA_L1",
      src: "MAD-2 §5.1",
    },
    {
      title: "Stage 7: Level 2 Viva (Max 60)",
      order: 7,
      maxScore: 60,
      academicCode: "VIVA_L2",
      src: "MAD-2 §5.2",
    },
    { title: "Stage 8: Final Grade Awarded", order: 8, academicCode: null, src: "MAD-2 §6.0" },
  ];

  const stagePageMap = {};
  let previousStageId = null;
  for (const st of stages) {
    const props = {
      Title: { title: [{ type: "text", text: { content: st.title } }] },
      "Item Type": { select: { name: "Stage" } },
      "Stage Order": { number: st.order },
      Status: { select: { name: "Not Started" } },
      Mandatory: { checkbox: true },
      Course: { relation: cs2006pCourseRelation },
      "Source / Section": { rich_text: [{ type: "text", text: { content: st.src } }] },
    };
    if (st.maxScore) {
      props["Max Score"] = { number: st.maxScore };
    }
    if (st.academicCode && academicItemMap[st.academicCode]) {
      props["Linked Academic Item"] = { relation: [{ id: academicItemMap[st.academicCode] }] };
    }
    if (previousStageId) {
      props["Prerequisite Stage"] = { relation: [{ id: previousStageId }] };
    }

    const page = await createPage({ database_id: ids.databases.projectTracker }, props);
    stagePageMap[st.order] = page.id;
    previousStageId = page.id;
    console.log(`   Created Stage ${st.order}: ${page.id}`);
  }

  // 3.2: 16 TMA V2 Requirements Checklist
  const requirements = [
    {
      title: "REQ-01: Flask RESTful API Backend Architecture",
      src: "TMA V2 §2.1",
      notes: "Modular blueprints, SQLAlchemy models, JWT token handling",
    },
    {
      title: "REQ-02: Vue.js 3 Single Page Application Frontend",
      src: "TMA V2 §2.2",
      notes: "Pinia state store, Vue Router navigation, responsive UI",
    },
    {
      title: "REQ-03: SQLite Database Architecture & Migrations",
      src: "TMA V2 §2.3",
      notes: "Enforce relational integrity, unique constraints, foreign keys",
    },
    {
      title: "REQ-04: Redis In-Memory Cache Implementation",
      src: "TMA V2 §2.4",
      notes: "Cache user dashboard queries, trek catalogs, 60s TTL invalidation",
    },
    {
      title: "REQ-05: Celery Background Task Queue Worker",
      src: "TMA V2 §2.5",
      notes: "Redis broker, independent worker process for heavy tasks",
    },
    {
      title: "REQ-06: Bootstrap Modern UI & Responsive Layout",
      src: "TMA V2 §2.6",
      notes: "Clean mobile-first design, interactive badges, modal dialogues",
    },
    {
      title: "REQ-07: RBAC & User Authentication (Admin, Staff, Trekker)",
      src: "TMA V2 §3.1",
      notes: "Role decorator guards, session persistence, secure password hashing",
    },
    {
      title: "REQ-08: Trek Lifecycle Management (Full CRUD)",
      src: "TMA V2 §3.2",
      notes: "Difficulty levels, altitude, duration, pricing, date scheduling",
    },
    {
      title: "REQ-09: Booking Flow & Concurrency Overbooking Guard",
      src: "TMA V2 §3.3",
      notes: "Atomic transactions, seat capacity validation, booking confirmation",
    },
    {
      title: "REQ-10: Multi-Criteria Trek Search & Dynamic Filters",
      src: "TMA V2 §3.4",
      notes: "Search by difficulty, price range, dates, duration, location",
    },
    {
      title: "REQ-11: Daily Reminder Celery Beat Scheduled Job",
      src: "TMA V2 §3.5",
      notes: "Beat scheduler at 18:00 IST for unconfirmed bookings via email/webhook",
    },
    {
      title: "REQ-12: Monthly Activity Celery Beat HTML Report",
      src: "TMA V2 §3.6",
      notes: "Monthly Jinja2 HTML report generator sent to Admin/Staff",
    },
    {
      title: "REQ-13: Asynchronous User-Triggered CSV Export",
      src: "TMA V2 §3.7",
      notes: "Background CSV generation, download alert banner when ready",
    },
    {
      title: "REQ-14: Clean Source Code ZIP Archive Package",
      src: "MAD-2 §4.1",
      notes: "Exclude node_modules, .venv, __pycache__, .git folder",
    },
    {
      title: "REQ-15: 5-Page PDF Documentation & AI Usage Declaration",
      src: "MAD-2 §4.3",
      notes: "Architecture diagram, API endpoints table, DB schema, AI ethics disclosure",
    },
    {
      title: "REQ-16: Video Presentation Walkthrough (<=10 mins)",
      src: "MAD-2 §4.5",
      notes: "Live code walkthrough, cold startup demonstration, feature overview",
    },
  ];

  for (const req of requirements) {
    const props = {
      Title: { title: [{ type: "text", text: { content: req.title } }] },
      "Item Type": { select: { name: "Requirement" } },
      Status: { select: { name: "Not Started" } },
      Mandatory: { checkbox: true },
      Course: { relation: cs2006pCourseRelation },
      "Source / Section": { rich_text: [{ type: "text", text: { content: req.src } }] },
      "Evidence / Notes": { rich_text: [{ type: "text", text: { content: req.notes } }] },
    };
    await createPage({ database_id: ids.databases.projectTracker }, props);
  }
  console.log(`   Seeded 16 TMA V2 Requirements.`);

  // 3.3: 12 Viva Prep Compliance Protocol Items
  const vivaItems = [
    {
      title: "VIVA-01: Dual Camera Hardware Setup (Face, Hands, Screen Visible)",
      src: "Viva Checklist §1",
      notes: "Primary webcam on face/hands, secondary phone camera capturing workspace",
    },
    {
      title: "VIVA-02: 10-Minute Cold Runtime Startup Rule",
      src: "Viva Checklist §2",
      notes: "Start Backend, Redis, Celery, and Vue frontend in < 10 mins from cold state",
    },
    {
      title: "VIVA-03: Checksum Verification against Submission ZIP",
      src: "Viva Checklist §3",
      notes: "SHA256 checksum of local directory matches submitted zip checksum",
    },
    {
      title: "VIVA-04: Git Repository Access & Collaborator Permission",
      src: "Git Helper §2",
      notes: "Ensure project repo is shared with evaluators with correct permissions",
    },
    {
      title: "VIVA-05: Pre-Installed Virtualenv / Node Modules",
      src: "Viva Checklist §4",
      notes: "Verified virtual environment and package dependencies installed prior to call",
    },
    {
      title: "VIVA-06: Zero AI/LLM Assistance Tooling in Code Editor",
      src: "Viva Checklist §5",
      notes: "GitHub Copilot, Cursor AI, and code autocompletion tools completely disabled",
    },
    {
      title: "VIVA-07: Student Identification Card Verification Ready",
      src: "Viva Checklist §6",
      notes: "IITM BS Student ID card physically present for verification",
    },
    {
      title: "VIVA-08: Working Microphone & Screen Share Audio Tested",
      src: "Viva Checklist §7",
      notes: "Google Meet audio/video hardware test completed 15 mins before viva",
    },
    {
      title: "VIVA-09: Terminal Command Cheat Sheet Ready",
      src: "Viva Checklist §8",
      notes: "List of run commands for Flask, Redis, Celery worker, Celery beat, Vite",
    },
    {
      title: "VIVA-10: Seed Database Loaded with Sample Treks/Users",
      src: "TMA V2 §4.0",
      notes: "Populated sample database with 5+ treks, admin, staff, and customer users",
    },
    {
      title: "VIVA-11: Redis Server & Celery Worker Running in Background",
      src: "TMA V2 §2.5",
      notes: "Redis ping returns PONG, Celery worker confirms task registration",
    },
    {
      title: "VIVA-12: Presentation Video Uploaded on Google Drive / Unlisted YouTube",
      src: "MAD-2 §4.5",
      notes: "Public/unlisted video URL tested in incognito window",
    },
  ];

  for (const v of vivaItems) {
    const props = {
      Title: { title: [{ type: "text", text: { content: v.title } }] },
      "Item Type": { select: { name: "Viva Prep" } },
      Status: { select: { name: "Not Started" } },
      Mandatory: { checkbox: true },
      Course: { relation: cs2006pCourseRelation },
      "Source / Section": { rich_text: [{ type: "text", text: { content: v.src } }] },
      "Evidence / Notes": { rich_text: [{ type: "text", text: { content: v.notes } }] },
    };
    await createPage({ database_id: ids.databases.projectTracker }, props);
  }
  console.log(`   Seeded 12 Viva Prep Protocol items.`);
  console.log(
    `   Total Project Tracker rows: ${stages.length + requirements.length + vivaItems.length} (Target: 37).`,
  );

  // 4. Seed Starter Personal Tasks (3 items)
  console.log("\n4. Seeding starter Personal Tasks...");
  const tasks = [
    {
      task: "Set up Trekking App Git repository & initial commit",
      course: "CS2006P",
      priority: "High",
      due: "2026-10-15",
      status: "To Do",
      notes: "Stage 0 prerequisite",
    },
    {
      task: "Review CS2005 Week 1 & 2 Java syntax and OOP concepts",
      course: "CS2005",
      priority: "Medium",
      due: "2026-10-17",
      status: "To Do",
      notes: "Preparation for A2 deadline",
    },
    {
      task: "Verify local environment: Python 3.11, Redis server, Node.js 20",
      course: "CS2006P",
      priority: "High",
      due: "2026-10-10",
      status: "In Progress",
      notes: "TMA development prerequisites",
    },
  ];

  for (const t of tasks) {
    const props = {
      Task: { title: [{ type: "text", text: { content: t.task } }] },
      Status: { select: { name: t.status } },
      Priority: { select: { name: t.priority } },
      Due: { date: { start: t.due } },
      Course: { relation: [{ id: coursePageMap[t.course] }] },
      Notes: { rich_text: [{ type: "text", text: { content: t.notes } }] },
    };
    await createPage({ database_id: ids.databases.personalTasks }, props);
  }
  console.log(`   Seeded 3 starter personal tasks.`);

  // Save map data to cache
  const seedCache = {
    coursePageMap,
    academicItemCount: academicItemsData.length,
    projectTrackerCount: stages.length + requirements.length + vivaItems.length,
  };
  fs.writeFileSync(path.resolve(__dirname, "seed_cache.json"), JSON.stringify(seedCache, null, 2));

  console.log(
    "\n✅ Phase 3 Complete! All 5 courses, 77 academic items, 37 project items, and personal tasks seeded successfully.",
  );
}

main().catch(console.error);
