// ============================================================================
// CANONICAL ACADEMIC EVENTS ARTIFACT FOR SUPABASE EDGE FUNCTIONS
// AUTO-GENERATED FROM src/data/events.ts. DO NOT EDIT DIRECTLY.
// Generator: scripts/generate_edge_canonical_events.ts
// Source Count: 51 events
// ============================================================================

export interface CanonicalEdgeEvent {
  id: string;
  title: string;
  type: string;
  date: string; // YYYY-MM-DD (Asia/Kolkata timezone)
  courseCode?: string;
  importance?: string;
  isHardCutoff?: boolean;
  description?: string;
}

export const CANONICAL_EDGE_EVENTS: CanonicalEdgeEvent[] = [
  {
    "id": "cutoff_term_registration",
    "title": "September 2026 Term Course Registration Window",
    "type": "eligibility_close",
    "date": "2026-09-23",
    "importance": "critical",
    "isHardCutoff": true,
    "description":
      "Official Term Course Registration window. Keep course list, required documents, and fee payment ready. Semester commences post-registration.",
  },
  {
    "id": "cutoff_week_04",
    "title": "OPPE 1 Eligibility Cutoff (Week 1-4 Assignments Freeze)",
    "type": "eligibility_close",
    "date": "2026-11-01",
    "importance": "critical",
    "isHardCutoff": true,
    "description":
      "Assignments 1-4 deadline. Irrevocably closes OPPE 1 eligibility (e.g. Java A2-A4 >= 40 & SCT clearance).",
  },
  {
    "id": "cutoff_se2001_oppe",
    "title": "SE2001 OPPE Eligibility Cutoff (BPT 1-3 Average Freeze)",
    "type": "eligibility_close",
    "date": "2026-11-20",
    "courseCode": "SE2001",
    "importance": "critical",
    "isHardCutoff": true,
    "description":
      "BPT 3 deadline. Average of first 3 BPTs >= 40/100 freezes to determine OPPE eligibility. BPT 4 strictly excluded.",
  },
  {
    "id": "cutoff_week_07",
    "title": "End Term Exam Eligibility Cutoff (Best 5 of First 7 Freeze)",
    "type": "eligibility_close",
    "date": "2026-11-25",
    "importance": "critical",
    "isHardCutoff": true,
    "description":
      "Hard cutoff for Best 5 of first 7 weekly assessments (>= 40/100). Irreversible gate to receive End Term hall ticket.",
  },
  {
    "id": "cutoff_week_08",
    "title": "CS2005 OPPE 2 Eligibility Cutoff (GrPAs A5-A8 Freeze)",
    "type": "eligibility_close",
    "date": "2026-11-29",
    "courseCode": "CS2005",
    "importance": "critical",
    "isHardCutoff": true,
    "description": "CS2005 Java weekly GrPAs (A5-A8) and best 5/7 cutoff for OPPE 2 scheduling.",
  },
  {
    "id": "cutoff_week_10",
    "title": "Term GAA Calculation Cutoff",
    "type": "eligibility_close",
    "date": "2026-12-13",
    "importance": "critical",
    "isHardCutoff": true,
    "description": "Weekly assignment cutoff for GAA calculations across all theory courses.",
  },
  {
    "id": "sct_window_01",
    "title": "OPPE System Compatibility Test (SCT) Window 1",
    "type": "eligibility_close",
    "date": "2026-10-30",
    "importance": "critical",
    "isHardCutoff": true,
    "description":
      "Mandatory System Compatibility Test (Window 1) for CS2005 (Java) & SE2001 (System Commands). Required for OPPE slot allocation.",
  },
  {
    "id": "sct_window_02",
    "title": "OPPE System Compatibility Test (SCT) Window 2",
    "type": "eligibility_close",
    "date": "2026-11-16",
    "importance": "critical",
    "isHardCutoff": true,
    "description":
      "Secondary / Re-attempt SCT Window 2 prior to OPPE 1 (Nov 22). OPPE 1 will not be scheduled if SCT is not completed.",
  },
  {
    "id": "sct_window_03",
    "title": "OPPE System Compatibility Test (SCT) Window 3",
    "type": "eligibility_close",
    "date": "2026-12-11",
    "importance": "critical",
    "isHardCutoff": true,
    "description":
      "Mandatory SCT Window 3 for OPPE 2 Day 1 candidates (Dec 20). System verification for secure proctored environment.",
  },
  {
    "id": "sct_window_04",
    "title": "OPPE System Compatibility Test (SCT) Window 4",
    "type": "eligibility_close",
    "date": "2026-12-28",
    "importance": "critical",
    "isHardCutoff": true,
    "description":
      "Final clearance SCT Window 4 prior to OPPE 2 Day 2 / ReOPPE (Jan 3). Absolute last chance to clear device and room setup.",
  },
  {
    "id": "exam_quiz_1",
    "title": "Quiz 1 (In-Centre Examination)",
    "type": "exam",
    "date": "2026-11-15",
    "importance": "critical",
    "description": "In-centre exam for CS2005, SE2001, CS2006, MS2001. Syllabus: Weeks 1 to 4.",
  },
  {
    "id": "exam_cs2005_oppe_1",
    "title": "CS2005 OPPE 1 (Programming Exam 1)",
    "type": "exam",
    "date": "2026-11-22",
    "courseCode": "CS2005",
    "importance": "critical",
    "description":
      "First online remote proctored programming exam for Java (Syllabus: Weeks 2–6). Slots allocated by course team.",
  },
  {
    "id": "exam_quiz_2",
    "title": "Quiz 2 (In-Centre Examination)",
    "type": "exam",
    "date": "2026-12-05",
    "importance": "critical",
    "description": "In-centre exam for CS2005, CS2006, MS2001. Syllabus: Weeks 3 to 8.",
  },
  {
    "id": "exam_se2001_oppe",
    "title": "SE2001 OPPE (System Commands Programming Exam)",
    "type": "exam",
    "date": "2026-12-20",
    "courseCode": "SE2001",
    "importance": "critical",
    "description":
      "Mandatory main OPPE based on Weeks 1-9 (Slot: 13:00–15:00 IST). Must attend this primary date to qualify for ReOPPE if failed.",
  },
  {
    "id": "exam_cs2005_oppe_2_day1",
    "title": "CS2005 OPPE 2 - Day 1 (Programming Exam 2)",
    "type": "exam",
    "date": "2026-12-20",
    "courseCode": "CS2005",
    "importance": "critical",
    "description":
      "Second online remote proctored programming exam Day 1 (Syllabus: Weeks 2–9). Slots 2A allocated by course team.",
  },
  {
    "id": "exam_cs2005_oppe_2_day2",
    "title": "CS2005 OPPE 2 - Day 2 (Programming Exam 2)",
    "type": "exam",
    "date": "2027-01-03",
    "courseCode": "CS2005",
    "importance": "critical",
    "description":
      "Second online remote proctored programming exam Day 2 (Syllabus: Weeks 2–9). Slots 2B/2D allocated by course team.",
  },
  {
    "id": "exam_se2001_reoppe",
    "title": "SE2001 Re-OPPE (System Commands)",
    "type": "exam",
    "date": "2027-01-03",
    "courseCode": "SE2001",
    "importance": "critical",
    "description":
      "Re-attempt for students who scored >= 20 in Dec 20 OPPE & stayed >= 90 mins in meet (Slot 2B: 13:00–15:00 IST).",
  },
  {
    "id": "exam_end_term",
    "title": "End Term Examination (In-Centre)",
    "type": "exam",
    "date": "2027-01-10",
    "importance": "critical",
    "description": "Comprehensive in-centre final exam covering all 12 weeks of content.",
  },
  {
    "id": "se2001_bpt_01_release",
    "title": "SE2001 BPT 1 Released",
    "type": "bpt_release",
    "date": "2026-10-16",
    "courseCode": "SE2001",
    "importance": "medium",
    "description": "BPT 1 released in course VM (4 questions). 7 days to complete.",
  },
  {
    "id": "se2001_bpt_01_due",
    "title": "SE2001 BPT 1 Submission Deadline",
    "type": "bpt_deadline",
    "date": "2026-10-23",
    "courseCode": "SE2001",
    "importance": "high",
    "description": "BPT 1 deadline. Counts towards 10% BPTA and OPPE eligibility gate.",
  },
  {
    "id": "se2001_bpt_02_release",
    "title": "SE2001 BPT 2 Released",
    "type": "bpt_release",
    "date": "2026-10-30",
    "courseCode": "SE2001",
    "importance": "medium",
    "description": "BPT 2 released in course VM (4 questions). 7 days to complete.",
  },
  {
    "id": "se2001_bpt_02_due",
    "title": "SE2001 BPT 2 Submission Deadline",
    "type": "bpt_deadline",
    "date": "2026-11-06",
    "courseCode": "SE2001",
    "importance": "high",
    "description": "BPT 2 deadline. Counts towards 10% BPTA and OPPE eligibility gate.",
  },
  {
    "id": "se2001_bpt_03_release",
    "title": "SE2001 BPT 3 Released",
    "type": "bpt_release",
    "date": "2026-11-13",
    "courseCode": "SE2001",
    "importance": "medium",
    "description": "BPT 3 released in course VM (4 questions). 7 days to complete.",
  },
  {
    "id": "se2001_bpt_03_due",
    "title": "SE2001 BPT 3 Submission Deadline",
    "type": "bpt_deadline",
    "date": "2026-11-20",
    "courseCode": "SE2001",
    "importance": "critical",
    "isHardCutoff": true,
    "description": "BPT 3 deadline. Average of first 3 BPTs >= 40 gates OPPE eligibility.",
  },
  {
    "id": "se2001_bpt_04_release",
    "title": "SE2001 BPT 4 Released",
    "type": "bpt_release",
    "date": "2026-12-04",
    "courseCode": "SE2001",
    "importance": "medium",
    "description": "BPT 4 released in course VM (4 questions). 7 days to complete.",
  },
  {
    "id": "se2001_bpt_04_due",
    "title": "SE2001 BPT 4 Submission Deadline",
    "type": "bpt_deadline",
    "date": "2026-12-11",
    "courseCode": "SE2001",
    "importance": "high",
    "description":
      "BPT 4 deadline. Counts towards 10% BPTA score. Does NOT affect OPPE eligibility gate.",
  },
  {
    "id": "cs2006p_git_tracker_open",
    "title": "MAD-2 Git Tracker Registration Opens (Milestone 0)",
    "type": "project_milestone",
    "date": "2026-10-10",
    "courseCode": "CS2006P",
    "importance": "high",
    "description":
      "Project submission portal opens and Git Tracker registration commences. Compulsory 0th milestone.",
  },
  {
    "id": "cs2006p_git_tracker_deadline",
    "title": "MAD-2 Git Tracker Registration Deadline",
    "type": "project_milestone",
    "date": "2026-10-25",
    "courseCode": "CS2006P",
    "importance": "critical",
    "isHardCutoff": true,
    "description":
      "Mandatory deadline to register GitHub repo on Git Tracker and invite AppDev team (MADII-cs2006). Prerequisite for evaluation.",
  },
  {
    "id": "cs2006p_bootcamp_01",
    "title": "MAD-2 Online Bootcamp 1 (Oct 20–29)",
    "type": "project_milestone",
    "date": "2026-10-20",
    "courseCode": "CS2006P",
    "importance": "high",
    "description":
      "10-day Online Bootcamp (Tuesday to Thursday). Recommended for early project kickoff, DB models, schema, authentication, and core milestones. Note: No offline bootcamp this term.",
  },
  {
    "id": "cs2006p_bootcamp_02",
    "title": "MAD-2 Online Bootcamp 2 (Nov 20–29)",
    "type": "project_milestone",
    "date": "2026-11-20",
    "courseCode": "CS2006P",
    "importance": "high",
    "description":
      "10-day Online Bootcamp (Friday to Sunday). Recommended for final feature integration, Celery jobs, Redis caching, and viva preparation. Note: No offline bootcamp this term.",
  },
  {
    "id": "cs2006p_validation_portal_open",
    "title": "MAD-2 Pre-Submission Validation Form Available",
    "type": "project_validation",
    "date": "2026-11-10",
    "courseCode": "CS2006P",
    "importance": "medium",
    "description":
      "Google Form inside portal active for testing ZIP archive structure. Repeatable check.",
  },
  {
    "id": "cs2006p_sub_track_prior",
    "title": "MAD-2 Project Submission (Prior Theory Passed Track)",
    "type": "project_submission",
    "date": "2026-11-17",
    "courseCode": "CS2006P",
    "importance": "critical",
    "isHardCutoff": true,
    "description":
      "Submission deadline for students who completed theory prior to Sept 2026. Evaluated out of 100.",
  },
  {
    "id": "cs2006p_viva_l1_window_prior",
    "title": "MAD-2 Level 1 Viva Cycle 1 Window",
    "type": "viva",
    "date": "2026-11-24",
    "courseCode": "CS2006P",
    "importance": "critical",
    "description":
      "Level 1 Viva window for Prior Theory submission cycle. 10-minute runtime rule strictly enforced.",
  },
  {
    "id": "cs2006p_viva_l2_window_prior",
    "title": "MAD-2 Level 2 Viva Cycle 1 Window",
    "type": "viva",
    "date": "2026-12-04",
    "courseCode": "CS2006P",
    "importance": "critical",
    "description": "Level 2 Viva with industry experts for students who scored >= 30 in L1 viva.",
  },
  {
    "id": "cs2006p_sub_track_current",
    "title": "MAD-2 Project Submission (Current Theory Track)",
    "type": "project_submission",
    "date": "2026-12-10",
    "courseCode": "CS2006P",
    "importance": "critical",
    "isHardCutoff": true,
    "description":
      "Submission deadline for students registered for CS2006 theory in Sept 2026. Evaluated out of 105 (capped at 100).",
  },
  {
    "id": "cs2006p_viva_l1_window_current",
    "title": "MAD-2 Level 1 Viva Cycle 2 Window",
    "type": "viva",
    "date": "2026-12-15",
    "courseCode": "CS2006P",
    "importance": "critical",
    "description": "Level 1 Viva window for Current Theory registered track.",
  },
  {
    "id": "cs2006p_viva_l2_window_current",
    "title": "MAD-2 Level 2 Viva Cycle 2 Window",
    "type": "viva",
    "date": "2026-12-26",
    "courseCode": "CS2006P",
    "importance": "critical",
    "description":
      "Level 2 Viva with industry experts for current theory track candidates who passed L1 with >= 30.",
  },
  {
    "id": "semester_start",
    "title": "September 2026 Academic Term Content Release",
    "type": "academic_milestone",
    "date": "2026-10-02",
    "importance": "medium",
    "description": "Course lectures, notes, and first week assignments released on course portal.",
  },
  {
    "id": "course_drop_deadline",
    "title": "Course Drop Window Deadline",
    "type": "academic_milestone",
    "date": "2026-10-18",
    "importance": "high",
    "isHardCutoff": true,
    "description": "Last day to drop courses without academic grade penalty.",
  },
  {
    "id": "assignment_weekly_w01",
    "title": "Week 1 Assignment Submission Deadline",
    "type": "assignment",
    "date": "2026-10-11",
    "importance": "medium",
    "description": "Standard submission deadline for Week 1 graded assignments.",
  },
  {
    "id": "assignment_weekly_w02",
    "title": "Week 2 Assignment Submission Deadline",
    "type": "assignment",
    "date": "2026-10-18",
    "importance": "medium",
    "description": "Standard submission deadline for Week 2 graded assignments.",
  },
  {
    "id": "assignment_weekly_w03",
    "title": "Week 3 Assignment Submission Deadline",
    "type": "assignment",
    "date": "2026-10-25",
    "importance": "medium",
    "description": "Standard submission deadline for Week 3 graded assignments.",
  },
  {
    "id": "assignment_weekly_w04",
    "title": "Week 4 Assignment Submission Deadline",
    "type": "assignment",
    "date": "2026-11-01",
    "importance": "high",
    "description": "Standard submission deadline for Week 4 graded assignments.",
  },
  {
    "id": "assignment_weekly_w05",
    "title": "Week 5 Assignment Submission Deadline",
    "type": "assignment",
    "date": "2026-11-11",
    "importance": "medium",
    "description": "Standard submission deadline for Week 5 graded assignments.",
  },
  {
    "id": "assignment_weekly_w06",
    "title": "Week 6 Assignment Submission Deadline",
    "type": "assignment",
    "date": "2026-11-18",
    "importance": "medium",
    "description": "Standard submission deadline for Week 6 graded assignments.",
  },
  {
    "id": "assignment_weekly_w07",
    "title": "Week 7 Assignment Submission Deadline",
    "type": "assignment",
    "date": "2026-11-25",
    "importance": "high",
    "description": "Standard submission deadline for Week 7 graded assignments.",
  },
  {
    "id": "assignment_weekly_w08",
    "title": "Week 8 Assignment Submission Deadline",
    "type": "assignment",
    "date": "2026-11-29",
    "importance": "medium",
    "description": "Standard submission deadline for Week 8 graded assignments.",
  },
  {
    "id": "assignment_weekly_w09",
    "title": "Week 9 Assignment Submission Deadline",
    "type": "assignment",
    "date": "2026-12-06",
    "importance": "medium",
    "description": "Standard submission deadline for Week 9 graded assignments.",
  },
  {
    "id": "assignment_weekly_w10",
    "title": "Week 10 Assignment Submission Deadline",
    "type": "assignment",
    "date": "2026-12-13",
    "importance": "high",
    "description": "Standard submission deadline for Week 10 graded assignments.",
  },
  {
    "id": "assignment_weekly_w11",
    "title": "Week 11 Assignment Submission Deadline",
    "type": "assignment",
    "date": "2026-12-23",
    "importance": "medium",
    "description": "Standard submission deadline for Week 11 graded assignments.",
  },
  {
    "id": "assignment_weekly_w12",
    "title": "Week 12 Assignment Submission Deadline",
    "type": "assignment",
    "date": "2026-12-23",
    "importance": "medium",
    "description": "Standard submission deadline for Week 12 graded assignments.",
  },
];
